// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./components/Banner/index.vue')['default']
    Bread: typeof import('./components/Bread/Bread.vue')['default']
    BreadItem: typeof import('./components/Bread/BreadItem.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImg: typeof import('element-plus/es')['ElImg']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    GoodsSku: typeof import('./components/GoodsSku/index.vue')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
